DROP DATABASE QLBH
GO
CREATE DATABASE QLBH

IF OBJECT_ID ('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG
GO
CREATE TABLE KHACHHANG
(
IDKH VARCHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(30) NULL,
SDT INT NULL,
DIACHI NVARCHAR(50) NULL
)

IF OBJECT_ID ('SANPHAM') IS NOT NULL
DROP TABLE SANPHAM
GO
CREATE TABLE SANPHAM
(
IDSanPham VARCHAR(10) PRIMARY KEY,
TEN NVARCHAR(30) NULL,
GIANHAP MONEY NULL,
SLNHAP INT NULL
)

IF OBJECT_ID ('PHIEUMUA') IS NOT NULL
DROP TABLE PHIEUMUA
GO
CREATE TABLE PHIEUMUA
(
IDPHIEUMUA VARCHAR(10) PRIMARY KEY,
IDKH VARCHAR(10)  NULL,
IDSanPham VARCHAR(10) NULL,
NGAYMUA DATETIME NULL,
CONSTRAINT FK_PHIEUMUA_SANPHAM FOREIGN KEY(IDSanPham) REFERENCES SANPHAM,
CONSTRAINT FK_PHIEUMUA_KHACHHANG FOREIGN KEY(IDKH) REFERENCES KHACHHANG
)

IF OBJECT_ID ('CTPHIEUMUA') IS NOT NULL
DROP TABLE CTPHIEUMUA
GO
CREATE TABLE CTPHIEUMUA
(
IDPHIEUMUA VARCHAR(10) NOT NULL,
IDSanPham VARCHAR(10) NOT NULL,
SLMUA INT NULL,
DONGIA MONEY NULL,
CONSTRAINT FK_CTPHIEUMUA_PHIEUMUA FOREIGN KEY(IDPHIEUMUA) REFERENCES PHIEUMUA,
CONSTRAINT FK_CTPHIEUMUA_SANPHAM FOREIGN KEY(IDSanPham) REFERENCES SANPHAM,
CONSTRAINT PK_CTPHIEUMUA PRIMARY KEY(IDPHIEUMUA,IDSanPham)
)



